# Forces new Travis-CI Infrastructure
sudo: false

language: php

env:
  global:
    - RUN_PHPCS="no"
    - USE_SCRUTINIZER="no"

matrix:
  include:
    - php: 7.0
      env: PHPUNIT_FLAGS="--coverage-clover=coverage.clover" RUN_PHPCS="yes" USE_SCRUTINIZER="yes"
    - php: hhvm

before_install:
  - composer self-update

install:
  - composer install

script:
  - ant clean
  - vendor/bin/phpunit --configuration phpunit.travis.xml $PHPUNIT_FLAGS
  - if [ "$USE_SCRUTINIZER" == "yes" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi;
  - if [ "$USE_SCRUTINIZER" == "yes" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi;
